drop table contacts if exists;

create table contacts (
  id bigint generated by default as identity (start with 1), 
  firstname   varchar(30),	
  lastname    varchar(30),
  telephone   varchar(15),
  email       varchar(30),
  created     timestamp,
  primary key (id)
)
